In [1]:
!pip install pennylane

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 23.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 67.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 82.9 MB/s eta 0:00:00


In [2]:
import pennylane as qml
from pennylane import numpy as np

basis embedding

In [3]:
wires = range(2)
basis_dev = qml.device("default.qubit", wires)

@qml.qnode(basis_dev)
def basis_encoder(data):
    qml.BasisEmbedding(data, wires)
    return qml.state()

basis_encoder([1, 1])

tensor([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j], requires_grad=True)

In [4]:
wires = range(2)
amp_dev = qml.device("default.qubit", wires)

@qml.qnode(amp_dev)
def amp_encoder(data):
    qml.AmplitudeEmbedding(data, wires)
    return qml.state()

amp_encoder([1/np.sqrt(2), 1/np.sqrt(2), 0, 0])


tensor([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j, 0.        +0.j], requires_grad=True)

In [5]:
wires = range(1)
angle_dev = qml.device("default.qubit", wires)

@qml.qnode(angle_dev)
def angle_encoder(data):
    qml.AngleEmbedding(features=data, wires=wires, rotation='X')
    return qml.state()

angle_encoder([1])


tensor([0.87758256+0.j        , 0.        -0.47942554j], requires_grad=True)

In [6]:
 wires = range(2)
dis_dev = qml.device("default.gaussian", wires)

@qml.qnode(dis_dev)
def dis_encoder(data):
    qml.DisplacementEmbedding(features=data, wires=range(2), method='amplitude', c=0.1)
    qml.QuadraticPhase(0.1, wires=1)
    return qml.expval(qml.NumberOperator(wires=1))

dis_encoder([2, 4])


array(16.47877626)

In [7]:
qaoa_dev = qml.device("default.qubit", wires=range(2))

@qml.qnode(qaoa_dev)
def qaoa_encoder(data, weights):
    qml.QAOAEmbedding(features=data, weights=weights, wires=range(2), local_field="Y")
    return qml.state()

features = [4+2j, 5]
shape = qml.QAOAEmbedding.shape(n_layers=2, n_wires=2)
